easy_admin:
    site_name: '<img width="75" height="70" src="/img/logoPoulpe.png">'
    design:
      brand_color: 'rgba(26, 188, 156, 0.85)'
      assets:
        favicon: '/img/logoIcon.gif'
        css:
          - '/css/sketchy/bootstrap.min.css'
          - '/css/admin.css'
      menu:
        - { entity: 'Product', icon: 'cube' }
        - { entity: 'Client', icon: 'user' }
        - { entity: 'Category', icon: 'tag' }
        - { entity: 'ProductPicture', icon: 'image' }
    list:
      max_results: 10
    show:
      max_results: 10
    entities:
      Product:
        label: 'Produits'
        class: App\Entity\Product
        list:
          title: "Les produits"
          actions: ['edit']
          fields:
            - id
            - {property: 'title', label: 'Nom'}
            - {property: 'unitPriceHT', label: 'Prix unitaire hors taxe'}
            - reference
            - {property: 'quantity', label: 'Quantité'}
            - description
            - {property: 'category.title', label: 'Categorie'}
        form:
          fields:
            - {property: 'title', label: 'Nom'}
            - {property: 'unitPriceHT', label: 'Prix unitaire hors taxe'}
            - reference
            - {property: 'quantity', label: 'Quantité'}
            - description
            - {property: 'category', type: 'entity', type_options: { class: 'App\Entity\category', choice_label: 'name'}}
            - {property: 'pictures', type: 'collection', type_options: { entry_type: 'App\Form\ProductPictureType', by_reference: false }}
        new:
          title:  'Ajouter un produit'
        edit:
          title:  'Modifier le produit'
      Category:
        label: 'Categories'
        class: App\Entity\Category
        list:
          title: "Les categories"
          fields:
            - id
            - {property: 'name', label: 'Nom'}
            - {property: 'title', label: 'Titre'}
            - {property: 'products.count', label: 'Nombre de produit'}
        form:
          fields:
            - {property: 'name', label: 'Nom', type: 'text'}
            - {property: 'title', label: 'Titre', type: 'textarea'}
        new:
          title:  'Ajouter une categorie'
        edit:
          title:  'Modifier la categorie'

      Client:
        label: 'Clients'
        class: App\Entity\Client
        disabled_actions: ['new']
        list:
          title: "Les clients"
          fields:
            - id
            - {property: 'login', label: 'Identifiant'}
            - {property: email, type: 'email'}
            - {property: 'lastName', label: 'Nom'}
            - {property: 'firstName', label: 'prénom'}
            - {property: 'phoneNumber', label: 'Numéro de telephone', type: 'tel'}
            - {property: 'avatarUrl', label: "Lien de l'avatar", type: image, base_path: '/img/'}
            - {property: 'confirmed', label: "Email confirmé"}
            - {property: 'roles', type: 'array'}
        edit:
          title:  'Modifier le client'
          form_options: { validation_groups: ['none'] }
          fields:
            - {property: 'login', label: 'Identifiant'}
            - {property: email, type: 'email'}
            - {property: 'lastName', label: 'Nom'}
            - {property: 'firstName', label: 'prénom'}
            - {property: 'phoneNumber', label: 'Numéro de telephone', type: 'tel'}
            - {property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' }}}

      ProductPicture:
        label: 'Images des produits'
        class: App\Entity\ProductPicture
        list:
          title: 'Les Images'
          fields:
            - id
            - {property: 'pictureName', label: "L'image", type: image, base_path: '/img/products'}
            - {property: 'product.title', label: 'Le produit'}
          actions:
            - { name: 'new', label: 'Ajouté une image'}
        new:
          title:  'Ajouté une image'
          fields:
          - {property: 'imageFile', type: vich_image, label: "l'image :"}
          - {property: 'product', type: 'entity', type_options: { class: 'App\Entity\product', choice_label: 'title', required: true}}
        edit:
          title:  "Modifier l'image"
          fields:
          - {property: 'imageFile', type: vich_image, label: "l'image :"}