swiftmailer:
    username: '%env(MAILER_USERNAME)%'
    password: '%env(MAILER_PASSWORD)%'
    host: 'smtp.gmail.com'
    port: 465
    encryption: ssl
    #url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
