twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      entityService: '@App\Services\TwigEntityService'
      paypalService: '@App\Services\PayPalService'
