version: '3'

services:
  web:
    #image: 'php:7.2-apache'
    build: .
    volumes:
      - '.docker/vhosts:/etc/apache2/sites-enabled'
      - '.:/var/www/html'
    ports:
      - '80:80'
    networks:
      - backend
networks:
  backend:
    external:
      name: backend
